profiles:
    default:
        model: openrouter/google/gemini-2.0-flash-exp:free
        strategy: wholefile
    qwen:
        model: openrouter/qwen/qwen-2.5-coder-32b-instruct
        strategy: searchreplace
    sonnet:
        model: openrouter/anthropic/claude-3.7-sonnet
        strategy: searchreplace
